Fix DB updates check

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -121,18 +121,20 @@ DB_PWD=${DB_URL_PARTS[1]}
 DB_JDBC_URL=jdbc:postgresql://${DB_URL_PARTS[2]}
 echo JDBC URL=$DB_JDBC_URL
 
-$CACHE_DIR/.maven/bin/mvn liquibase:updateSQL --non-recursive -Dliquibase.url=$DB_JDBC_URL -Dliquibase.username=$DB_USER -Dliquibase.password=$DB_PWD -B -Duser.home=$BUILD_DIR -Dmaven.repo.local=$CACHE_DIR/.m2/repository -s $CACHE_DIR/.m2/settings.xml
+$CACHE_DIR/.maven/bin/mvn liquibase:updateSQL -f payments/pom.xml -Dliquibase.url=$DB_JDBC_URL -Dliquibase.username=$DB_USER -Dliquibase.password=$DB_PWD -B -Duser.home=$BUILD_DIR -Dmaven.repo.local=$CACHE_DIR/.m2/repository -s $CACHE_DIR/.m2/settings.xml
 
 echo "------> listing dirs:"
 ls $BUILD_DIR
 
-UPDATE_SQL_FILE=$BUILD_DIR/target/liquibase/migrate.sql.bkup
-#if grep -m 1 -q ^\\s\*\\w\\+ "$UPDATE_SQL_FILE"; then
-if grep -q '--' $UPDATE_SQL_FILE; then
-    echo -------> Need to update DB - aborting deploy
+UPDATE_SQL_FILE=$BUILD_DIR/payments/target/liquibase/migrate.sql
+if grep -m 1 -q ^\\s\*\\w\\+ "$UPDATE_SQL_FILE"; then
+    echo "-------> Need to update DB - aborting deploy"
+    exit 1
+elif [ ! -f $UPDATE_SQL_FILE ]; then
+    echo "-------> Buildpack is broken - can't check if DB needs update. Aborting deploy."
     exit 1
 else
-    echo ------> DB is up to date, OK to depoy
+    echo "------> DB is up to date, OK to depoy"
 fi
 
 # build app
